---
title: "R_analyses"
author: "EisenRa"
date: "2021-06-10"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Load packages, import data

```{r}
library(phyloseq)
library(qiime2R)
library(dplyr)
library(svglite)
library(cowplot)
library(gplots)
library(ggplot2)
library(scales)
library(ggpubr)
library(tidyr)
library(knitr)
library(microbiome)
library(VennDiagram)
library(ggVennDiagram)
library(forcats)
library(tidyverse)
library(ggmap)
library(ggrepel)
library(osmdata)


#Import data into phyloseq object
ps <- qza_to_phyloseq(
  features = "analysis/QIIME2/Koala-table.qza",
  tree = "analysis/QIIME2/Koala-sepp-tree.qza",
  taxonomy = "analysis/QIIME2/Koala-SILVA-138.qza",
  metadata = "analysis/QIIME2/Koala_Metadata.tsv"
)


```

# Create map of samples
```{r}
#Load sample metadata
data <- read.csv("analysis/QIIME2/Koala_Metadata.tsv", sep = '\t')
#Create a data frame of unique values to make plotting later easier
data.distinct <- data %>% distinct(Location_sampled, GPS_area_lat, GPS_area_lon)
  
#Determine size of map I need by looking at max/min lat/long data
latmin <- min(data$GPS_area_lat) - 9
latmax <- max(data$GPS_area_lat) + 3
longmin <- min(data$GPS_area_lon) - 3
longmax <- max(data$GPS_area_lon) + 3

mapbounds = c(longmin, latmin, longmax, latmax)

#Plot
map <- get_map(location = mapbounds, source = "osm", maptype = "hybrid")

ggmap(map) +
  geom_point(data = data.distinct, 
             aes(x = GPS_area_lon, y = GPS_area_lat), size = 6, shape = "triangle") +
  geom_text_repel(data = data.distinct, 
                  aes(x = GPS_area_lon, y = GPS_area_lat, label = Location_sampled), 
                  size = 7, box.padding = 3, fontface = "bold")
```


# Diversity through time plots
```{r}
#Import data using qiime2R
metadata <- read.csv("analysis/QIIME2/Koala_Metadata.tsv", sep = '\t')
evenness.cleland <- read_qza("analysis/QIIME2/Core-metrics-Cleland-36622/evenness_vector.qza")
richness.cleland <- read_qza("analysis/QIIME2/Core-metrics-Cleland-36622/observed_features_vector.qza")
evenness.mtlagoon <- read_qza("analysis/QIIME2/Core-metrics-MtLagoon-36622/evenness_vector.qza")
richness.mtlagoon <- read_qza("analysis/QIIME2/Core-metrics-MtLagoon-36622/observed_features_vector.qza")

#This moves the sample names to a new column that matches the metadata and allows them to be merged
evenness.cleland <- evenness.cleland$data %>% rownames_to_column("SampleID") 
richness.cleland <- richness.cleland$data %>% rownames_to_column("SampleID")
evenness.mtlagoon <- evenness.mtlagoon$data %>% rownames_to_column("SampleID") 
richness.mtlagoon <- richness.mtlagoon$data %>% rownames_to_column("SampleID")

#Now join the diversity values to the main metadata file
metadata.evenness.cleland <- metadata %>% left_join(evenness.cleland)
metadata.richness.cleland <- metadata %>% left_join(richness.cleland)
metadata.evenness.mtlagoon <- metadata %>% left_join(evenness.mtlagoon)
metadata.richness.mtlagoon <- metadata %>% left_join(richness.mtlagoon)

#Summary stats for diversity results
coalesce(metadata.evenness.mtlagoon, metadata.evenness.cleland) %>%
  group_by(Location_sampled) %>%
  summarize(mean = mean(pielou_evenness), std = sd(pielou_evenness))

coalesce(metadata.richness.mtlagoon, metadata.richness.cleland) %>%
  group_by(Location_sampled) %>%
  summarize(mean = mean(observed_features), std = sd(observed_features))

#Set ggplot theme
theme_RE <- theme(axis.text.x = element_text(size=20), 
                  axis.text.y = element_text(size=20),
                  axis.title.x = element_text(size=24, face="bold"),
                  axis.title.y = element_text(size=24, face="bold"),
                  axis.line = element_line(colour = "black"),
                  #Background panel
                  panel.background = element_rect(fill = "White"),
                  panel.grid.major = element_line(colour = "white"), 
                  panel.grid.minor = element_line(colour = "white"),
                  #Legend
                  legend.title = element_text(size=0),
                  legend.text = element_text(size=16),
                  legend.key = element_rect(fill = "white", color = NA),
                  legend.position = c(0.5, 0.18),
                  legend.direction = "horizontal",
                  legend.key.size = unit(3.5, "line"))

#Set colours
cbp2_cleland <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
                  "#F0E442", "#0072B2", "#D55E00")

cbp2_mtlagoon <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288")


plot.evenness.cleland <- metadata.evenness.cleland %>%
  filter(!is.na(metadata.evenness.cleland$pielou_evenness)) %>%
  ggplot(aes(x=Collection_number, y=pielou_evenness, color=Koala)) +
  geom_line(size = 5) +
  geom_point(size = 8) +
  scale_x_continuous(breaks = seq(1, 8, 1), labels = c(
    "1" = "4", "2" = "8", "3" = "12", "4" = "16", 
    "5" = "20", "6" = "24", "7" = "28", "8" = "32"
  )) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  xlab(" ") +
  ylab("pielou evenness") +
  scale_color_manual(values = cbp2_cleland) +
  theme_RE


plot.evenness.mtlagoon <- metadata.evenness.mtlagoon %>%
  filter(!is.na(metadata.evenness.mtlagoon$pielou_evenness)) %>%
  ggplot(aes(x=Collection_number, y=pielou_evenness, color=Koala)) +
  geom_line(size = 5) +
  geom_point(size = 8) +
  scale_x_continuous(breaks = seq(1, 8, 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  xlab(" ") +
  ylab(" ") +
  scale_color_manual(values = cbp2_mtlagoon) +
  theme_RE


plot.richness.cleland <- metadata.richness.cleland %>%
  filter(!is.na(metadata.richness.cleland$observed_features)) %>%
  ggplot(aes(x=Collection_number, y=observed_features, color=Koala)) +
  geom_line(size = 5) +
  geom_point(size = 8) +
  scale_x_continuous(breaks = seq(1, 8, 1), labels = c(
    "1" = "4", "2" = "8", "3" = "12", "4" = "16", 
    "5" = "20", "6" = "24", "7" = "28", "8" = "32"
  )) +
  scale_y_continuous(limits = c(1, 280), breaks = seq(0, 300, 50)) +
  xlab("Day") +
  ylab("ASV richness") +
  scale_color_manual(values = cbp2_cleland) +
  theme_RE


plot.richness.mtlagoon <- metadata.richness.mtlagoon %>%
  filter(!is.na(metadata.richness.mtlagoon$observed_features)) %>%
  ggplot(aes(x=Collection_number, y=observed_features, color=Koala)) +
  geom_line(size = 5) +
  geom_point(size = 8) +
  scale_x_continuous(breaks = seq(1, 8, 1)) +
  scale_y_continuous(limits = c(1, 280), breaks = seq(0, 300, 50)) +
  xlab("Month") +
  ylab(" ") +
  scale_color_manual(values = cbp2_mtlagoon) +
  theme_RE 


ggarrange(plot.evenness.cleland, plot.evenness.mtlagoon,
          plot.richness.cleland, plot.richness.mtlagoon,
          nrow = 2, ncol = 2, common.legend = FALSE, labels = c("A)", "B)", "C)", "D)"), 
          font.label = list(size=18, face="bold", color="black"))

```


# PCoA figures
```{r}
#QIIME2 generated PCoA matrices
pcoa_uwUniFrac_all <- read_qza(
  "analysis/QIIME2/Core-metrics-both-populations-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_all <- read_qza(
  "analysis/QIIME2/Core-metrics-both-populations-36622/weighted_unifrac_pcoa_results.qza")
pcoa_uwUniFrac_Cleland <- read_qza(
  "analysis/QIIME2/Core-metrics-Cleland-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_Cleland <- read_qza(
  "analysis/QIIME2/Core-metrics-Cleland-36622/weighted_unifrac_pcoa_results.qza")
pcoa_uwUniFrac_MtLagoon <- read_qza(
  "analysis/QIIME2/Core-metrics-MtLagoon-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_MtLagoon <- read_qza(
  "analysis/QIIME2/Core-metrics-MtLagoon-36622/weighted_unifrac_pcoa_results.qza")

#Load metadata
metadata_pcoa <- read.csv("analysis/QIIME2/Koala_Metadata.tsv", sep = '\t')

#Colour palette
cbp2_beta <- c("orange", "black", "red", "blue")

#Create a function to plot PCoAs using ggplot2
plot.PCoA <- function(pcoa, pcx, pcy, color) {
  
  pcoa$data$Vectors %>%
  rename("SampleID"=SampleID) %>%
  left_join(metadata_pcoa) %>%
  arrange(Collection_number) %>%
  
  ggplot(aes_string(x=paste0("PC", pcx), y=paste0("PC", pcy), color=color)) +
  scale_x_reverse() +
  geom_point(size=7.5) +
#  stat_ellipse(type = "norm", aes(fill = Koala)) +
  geom_path() +
  geom_text(aes(label = Collection_number), color = "black", fontface = "bold") +
    
  xlab(paste0("PC", pcx, ": " , round(100*pcoa$data$ProportionExplained[pcx]), "%")) +
  ylab(paste0("PC", pcy, ": " , round(100*pcoa$data$ProportionExplained[pcy]), "%")) +
  #Custom manual colours
  scale_colour_manual(values=cbp2_beta) +
  
  theme(axis.text.x = element_text(face="bold", size=24), 
        axis.text.y = element_text(face="bold", size=24),
        axis.title.x = element_text(size=30, face="bold"),
        axis.title.y = element_text(size=30, face="bold"),
        axis.line = element_line(colour = "black"),
        #Background panel
        panel.background = element_rect(fill = "White"),
        panel.grid.major = element_line(colour = "white"), 
        panel.grid.minor = element_line(colour = "white"),
        #Legend
        legend.title = element_text(size=0),
        legend.text = element_text(size=24),
        legend.key = element_rect(fill = "white", color = NA),
        legend.key.size = unit(3.5, "line"))

#Save image
ggsave(filename = paste0("output/", deparse(substitute(pcoa)), "_", color, "_PC", pcx, "-", pcy, ".png"), 
       width = 20, height = 11, dpi = 300)

}

##Run through plots
#Mtlagoon + Cleland
plot.PCoA(pcoa_uwUniFrac_all, 1, 2, "Population")
plot.PCoA(pcoa_uwUniFrac_all, 1, 3, "Population")

plot.PCoA(pcoa_wUniFrac_all, 1, 2, "Population")
plot.PCoA(pcoa_wUniFrac_all, 1, 3, "Population")


#Cleland only

cbp2_beta <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00")

plot.PCoA(pcoa_uwUniFrac_Cleland, 1, 2, "Koala")
plot.PCoA(pcoa_uwUniFrac_Cleland, 1, 3, "Koala")

plot.PCoA(pcoa_wUniFrac_Cleland, 1, 2, "Koala")
plot.PCoA(pcoa_wUniFrac_Cleland, 1, 3, "Koala")


#MtLagoon only
cbp2_beta <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288")

plot.PCoA(pcoa_uwUniFrac_MtLagoon, 1, 2, "Koala")
plot.PCoA(pcoa_uwUniFrac_MtLagoon, 1, 3, "Koala")

plot.PCoA(pcoa_wUniFrac_MtLagoon, 1, 2, "Koala")
plot.PCoA(pcoa_wUniFrac_MtLagoon, 1, 3, "Koala")

```

# Taxonomic bar plots
```{r}

#Collapse to family level
ps.family <- tax_glom(ps, taxrank = "Family", NArm = FALSE)

#Extract top 20 most abundant family names, bind to ps sampledata
top20families = names(sort(taxa_sums(ps.family), TRUE)[1:20])
taxtab20 = cbind(tax_table(ps.family), family_20 = NA)
taxtab20[top20families, "family_20"] <- as(tax_table(ps.family)
                                           [top20families, "Family"], "character")
tax_table(ps.family) <- tax_table(taxtab20)

ps.family.ra <- transform_sample_counts(ps.family, function(x) 100 * x/sum(x))

#Melt into a dataframe
pd.family <- psmelt(ps.family.ra)

#Replace NA with 'other', for plotting purposes
pd.family <- arrange(pd.family, Koala_Collection)
pd.family$family_20[is.na(pd.family$family_20)] <- c("Other")

#Plot em
pd.family.plot <- ggplot(pd.family, aes(x = Koala_Collection, y = Abundance,
                                        fill = fct_reorder(family_20, -Abundance))) +
  geom_bar(stat = "identity") +
  facet_grid(~Location_sampled, scales = "free", space ='free') +
  labs(x = "", y = "Relative abundance") +
#  scale_y_continuous(labels = scales::percent_format()) +
  theme(axis.text.y = element_text(size=16, face = 'bold'),
        axis.title.y = element_text(size=16, face = 'bold'),
        axis.ticks.y = element_line(size = 1),
        axis.text.x = element_text(size = 13, angle = 55, hjust = 1),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        legend.position = "top",
        strip.text = element_text(face = "bold", size = 14),
        panel.background = element_blank()
        ) +
  scale_fill_manual(values = 
      c("Bacteroidaceae" = "#228B22", "[Eubacterium]_coprostanoligenes_group" = "#3CB371",
        "Akkermansiaceae" = "#2E8B57", "Tannerellaceae" = "#8FBC8F",
        "Christensenellaceae" = "#191970", "Clostridiaceae" = "#db6d00",
        "Paludibacteraceae" = "#66CCEE", "Muribaculaceae" = "#FF1493",
        "Erysipelatoclostridiaceae" = "#0000FF", "Lachnospiraceae" = "#B8860B",
        "Oscillospiraceae" = "#FF6347", "Acidaminococcaceae" = "#F0E68C",
        "Pasteurellaceae" = "#FF69B4", "Desulfovibrionaceae" = "#FFC0CB",
        "Prevotellaceae" = "#FFFF00", "Rikenellaceae" = "#00FF7F",
        "Ruminococcaceae" = "#b66dff", "vadinHA49" = "#FF00FF",
        "Synergistaceae" = "#8B0000", "Gastranaerophilales" = "#000000", "Other" = "#808080")
  )

ggsave(filename = "output/Family_Taxa_Plot.png", 
       width = 20, height = 12, dpi = 300)

```

# Mean relative abundances of select microbial families between CL/ML
```{r}
#Merge samples by geographic location
ps.family.merged <- merge_samples(ps.family, "Location_sampled")

ps.family.merged.relab <- transform_sample_counts(ps.family.merged, function(x) x / sum(x))
ps.family.merged.relab@otu_table <- phyloseq::t(ps.family.merged.relab@otu_table)
#Had to transpose otu table, as merge_samples flips it for some reason...

ps.family.merged.relab.tax <- as.data.frame(tax_table(ps.family.merged.relab))
ps.family.merged.relab.otu.and.tax <- cbind(ps.family.merged.relab.tax, 
                                              ps.family.merged.relab@otu_table)

DT::datatable(ps.family.merged.relab.otu.and.tax)

```


# ASV-level analyses
```{r}
library(gridExtra)

options(digits=3)

##Rarefy ASV table
ps.rar <- rarefy_even_depth(ps, rngseed=666, sample.size = 36622)

##How many ASVs are always present in a given koala through time?
#Create a list of each subset that I want (per koala)
koala_list <- c(
  ps.blaze <- subset_samples(ps.rar, Koala=="Blaze"),
  ps.byron <- subset_samples(ps.rar, Koala=="Byron"),
  ps.cin <- subset_samples(ps.rar, Koala=="Cin"),
  ps.claudette <- subset_samples(ps.rar, Koala=="Claudette"),
  ps.george <- subset_samples(ps.rar, Koala=="George"),
  ps.leo <- subset_samples(ps.rar, Koala=="Leo"),
  ps.lola <- subset_samples(ps.rar, Koala=="Lola"),
  ps.phasco <- subset_samples(ps.rar, Koala=="Phasco"),
  ps.reus <- subset_samples(ps.rar, Koala=="Reus"),
  ps.theo <- subset_samples(ps.rar, Koala=="Theo"),
  ps.tos <- subset_samples(ps.rar, Koala=="Tos"),
  ps.uno <- subset_samples(ps.rar, Koala=="Uno")
)

#Create functions to use in loop
gen_x <- function(numasv){
  print(length(taxa_names(filter_taxa(numasv, function(x) sum(x) > 0 , TRUE))))
}
gen_y <- function(numcore){
  print(length(taxa_names(core(numcore, detection =1, prevalence =0.999))))
}
gen_z <- function(relabcore){
  print(mean(sample_sums(core(relabcore, detection =1, prevalence =0.999))) / mean(sample_sums(relabcore)))
}

#Create dataframe of length koalalist
ASVresults <- data.frame(totalASVs_per_koala=rep(0,length(koala_list)),
                      total_core_ASVs=rep(0,length(koala_list)),
                      mean_rel_abun_core_ASVs=rep(0,length(koala_list)))
row.names(ASVresults) <- sort(unique(ps.rar@sam_data$Koala))

#Loop over each subsetted phyloseq object, outputting results into the dataframe!
for (ps in 1:length(koala_list)){
  x <- gen_x(koala_list[[ps]])
  y <- gen_y(koala_list[[ps]])
  z <- gen_z(koala_list[[ps]])
  ASVresults[ps, 1] <- x
  ASVresults[ps, 2] <- y
  ASVresults[ps, 3] <- z
}

write.csv(ASVresults, file = "output/ASVresults.csv")

#Print summary stats of ASV results:
select(ASVresults, totalASVs_per_koala) %>%
  summarize(., mean=mean(totalASVs_per_koala), SD=sd(totalASVs_per_koala))
select(ASVresults, total_core_ASVs) %>%
  summarize(., mean=mean(total_core_ASVs), SD=sd(total_core_ASVs))
select(ASVresults, mean_rel_abun_core_ASVs) %>%
  summarize(., mean=mean(mean_rel_abun_core_ASVs), SD=sd(mean_rel_abun_core_ASVs))

##How many 100% core ASVs are shared between all koala inviduals?
core(ps.rar, detection=1, prevalence=0.999) %>%
  otu_table()
#None, it seems.

##What about 100% core ASVs within CL and ML?
#Add ASV column to tax_table for easy subsetting:
ps.rar.ASV <- ps.rar  
tax_table(ps.rar.ASV) <- cbind(tax_table(ps.rar.ASV), 
    rownames(tax_table(ps.rar.ASV)))
colnames(tax_table(ps.rar.ASV)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ASV")

#Cleland
subset_samples(ps.rar.ASV, Location_sampled=="Cleland") %>%
  core(., detection=1, prevalence=0.999) %>%
  otu_table()

#Get taxonomic information for the most abundant of these CL 100% core ASVs:
subset_taxa(ps.rar.ASV, ASV=="593a5c45dd38f6d9ec369b9b2679997f") %>%
  tax_table()

#What is the relative abundance of this 100% core CL ASV?
ASV.sum <- subset_samples(ps.rar.ASV, Location_sampled=="Cleland") %>%
  subset_taxa(., ASV=="593a5c45dd38f6d9ec369b9b2679997f") %>%
  sample_sums()
TOT.sum <- subset_samples(ps.rar.ASV, Location_sampled=="Cleland") %>%
  sample_sums()

mean(ASV.sum/TOT.sum)
sd(ASV.sum/TOT.sum)

#Mountain Lagoon
subset_samples(ps.rar.ASV, Location_sampled=="Mountain_Lagoon") %>%
  core(., detection=1, prevalence=0.999) %>%
  otu_table()

subset_taxa(ps.rar.ASV, ASV=="ce3b37d15aee37e4213c2d13ad8b1b1a") %>%
  tax_table()
subset_taxa(ps.rar.ASV, ASV=="f3521f355b29e7f7c878d616495def33") %>%
  tax_table()

ML.ASV.sum.1 <- subset_samples(ps.rar.ASV, Location_sampled=="Mountain_Lagoon") %>%
  subset_taxa(., ASV=="ce3b37d15aee37e4213c2d13ad8b1b1a") %>%
  sample_sums()
ML.ASV.sum.2 <- subset_samples(ps.rar.ASV, Location_sampled=="Mountain_Lagoon") %>%
  subset_taxa(., ASV=="f3521f355b29e7f7c878d616495def33") %>%
  sample_sums()
ML.TOT.sum <- subset_samples(ps.rar.ASV, Location_sampled=="Mountain_Lagoon") %>%
  sample_sums()

mean(ML.ASV.sum.1/ML.TOT.sum)
sd(ML.ASV.sum.1/ML.TOT.sum)
mean(ML.ASV.sum.2/ML.TOT.sum)
sd(ML.ASV.sum.2/ML.TOT.sum)

```

##How many ASVs (non-core) are shared between CL and ML koalas?
```{r}
#Subset samples by population and save feature tables
ps.CL <- subset_samples(ps.rar.ASV, Location_sampled == "Cleland")
ps.ML <- subset_samples(ps.rar.ASV, Location_sampled == "Mountain_Lagoon")

ps.CL.table <- otu_table(ps.CL)
ps.ML.table <- otu_table(ps.ML)

#For each ASV (row), if abundance > 0, print ASV (rowname) to a vector 
venn.CL <- rownames(ps.CL.table[ apply(ps.CL.table, MARGIN = 1, function(x) any(x > 0))])

venn.ML <- rownames(ps.ML.table[ apply(ps.ML.table, MARGIN = 1, function(x) any(x > 0))])

ppn.comparison <- list("Cleland" = venn.CL, "Mountain Lagoon" = venn.ML)

venn.diagram(ppn.comparison, print.mode = c("raw","percent"), fill = c("red", "blue"), inverted = TRUE, 
             imagetype = "png", filename = "output/Venn.png", cat.pos = c(0,0))

subset_taxa(ps.CL, ASV==venn.CL)

shared_ASVS <- get_region_items(ppn.comparison) %>%
  .$AB

percent(mean(sample_sums(prune_taxa(shared_ASVS, ps.CL))) /
        mean(sample_sums(ps.CL)))

percent(mean(sample_sums(prune_taxa(shared_ASVS, ps.ML))) /
        mean(sample_sums(ps.ML)))

```





#Software/package versions
```{r}
sessionInfo()
```



