---
title: "R_analyses"
author: "EisenRa"
date: "2020-02-10"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Load packages, import data

```{r}
library(phyloseq)
library(qiime2R)
library(dplyr)
library(svglite)
library(cowplot)
library(gplots)
library(ggplot2)
library(scales)
library(ggpubr)
library(tidyr)
library(knitr)
library(microbiome)
library(VennDiagram)
library(ggVennDiagram)
library(eulerr)
library(forcats)


#Import data into phyloseq object
ps <- qza_to_phyloseq(
  features = "analysis/QIIME2/Koala-table.qza",
  tree = "analysis/QIIME2/Koala-sepp-tree.qza",
  taxonomy = "analysis/QIIME2/Koala-SILVA-138.qza",
  metadata = "analysis/QIIME2/Koala_Metadata.tsv"
)

#QIIME2 generated PCoA matrices
pcoa_uwUniFrac_all <- read_qza(
  "analysis/QIIME2/Core-metrics-both-populations-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_all <- read_qza(
  "analysis/QIIME2/Core-metrics-both-populations-36622/weighted_unifrac_pcoa_results.qza")
pcoa_uwUniFrac_Cleland <- read_qza(
  "analysis/QIIME2/Core-metrics-Cleland-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_Cleland <- read_qza(
  "analysis/QIIME2/Core-metrics-Cleland-36622/weighted_unifrac_pcoa_results.qza")
pcoa_uwUniFrac_MtLagoon <- read_qza(
  "analysis/QIIME2/Core-metrics-MtLagoon-36622/unweighted_unifrac_pcoa_results.qza")
pcoa_wUniFrac_MtLagoon <- read_qza(
  "analysis/QIIME2/Core-metrics-MtLagoon-36622/weighted_unifrac_pcoa_results.qza")

```

## PCoA figures
```{r}
#Load metadata
metadata_pcoa <- read.csv("analysis/QIIME2/Koala_Metadata.tsv", sep = '\t')

#Colour palette
cbp2_beta <- c("orange", "black", "red", "blue")

#Create a function to plot PCoAs using ggplot2
plot.PCoA <- function(pcoa, pcx, pcy, color) {
  
  pcoa$data$Vectors %>%
  rename("SampleID"=SampleID) %>%
  left_join(metadata_pcoa) %>%
  arrange(Collection_number) %>%
  
  ggplot(aes_string(x=paste0("PC", pcx), y=paste0("PC", pcy), color=color)) +
  scale_x_reverse() +
  geom_point(size=7.5) +
#  stat_ellipse(type = "norm", aes(fill = Koala)) +
  geom_path() +
  geom_text(aes(label = Collection_number), color = "black", fontface = "bold") +
    
  xlab(paste0("PC", pcx, ": " , round(100*pcoa$data$ProportionExplained[pcx]), "%")) +
  ylab(paste0("PC", pcy, ": " , round(100*pcoa$data$ProportionExplained[pcy]), "%")) +
  #Custom manual colours
  scale_colour_manual(values=cbp2_beta) +
  
  theme(axis.text.x = element_text(face="bold", size=24), 
        axis.text.y = element_text(face="bold", size=24),
        axis.title.x = element_text(size=30, face="bold"),
        axis.title.y = element_text(size=30, face="bold"),
        axis.line = element_line(colour = "black"),
        #Background panel
        panel.background = element_rect(fill = "White"),
        panel.grid.major = element_line(colour = "white"), 
        panel.grid.minor = element_line(colour = "white"),
        #Legend
        legend.title = element_text(size=0),
        legend.text = element_text(size=24),
        legend.key = element_rect(fill = "white", color = NA),
        legend.key.size = unit(3.5, "line"))

#Save image
ggsave(filename = paste0("output/", deparse(substitute(pcoa)), "_", color, "_PC", pcx, "-", pcy, ".png"), 
       width = 20, height = 11, dpi = 300)

}

##Run through plots
#Mtlagoon + Cleland
plot.PCoA(pcoa_uwUniFrac_all, 1, 2, "Population")
plot.PCoA(pcoa_uwUniFrac_all, 1, 3, "Population")

plot.PCoA(pcoa_wUniFrac_all, 1, 2, "Population")
plot.PCoA(pcoa_wUniFrac_all, 1, 3, "Population")


#Cleland only

cbp2_beta <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

plot.PCoA(pcoa_uwUniFrac_Cleland, 1, 2, "Koala")
plot.PCoA(pcoa_uwUniFrac_Cleland, 1, 3, "Koala")

plot.PCoA(pcoa_wUniFrac_Cleland, 1, 2, "Koala")
plot.PCoA(pcoa_wUniFrac_Cleland, 1, 3, "Koala")


#MtLagoon only
cbp2_beta <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
               "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

plot.PCoA(pcoa_uwUniFrac_MtLagoon, 1, 2, "Koala")
plot.PCoA(pcoa_uwUniFrac_MtLagoon, 1, 4, "Koala")

plot.PCoA(pcoa_wUniFrac_MtLagoon, 1, 2, "Koala")
plot.PCoA(pcoa_wUniFrac_MtLagoon, 1, 4, "Koala")

```

#Taxonomic bar plots
```{r}

#Collapse to family level
ps.family <- tax_glom(ps, taxrank = "Family", NArm = FALSE)

#Extract top 20 most abundant family names, bind to ps sampledata
top20families = names(sort(taxa_sums(ps.family), TRUE)[1:20])
taxtab20 = cbind(tax_table(ps.family), family_20 = NA)
taxtab20[top20families, "family_20"] <- as(tax_table(ps.family)
                                           [top20families, "Family"], "character")
tax_table(ps.family) <- tax_table(taxtab20)

ps.family.ra <- transform_sample_counts(ps.family, function(x) 100 * x/sum(x))

#Melt into a dataframe
pd.family <- psmelt(ps.family.ra)

#Replace NA with 'other', for plotting purposes
pd.family <- arrange(pd.family, Koala_Collection)
pd.family$family_20[is.na(pd.family$family_20)] <- c("Other")

#Plot em
pd.family.plot <- ggplot(pd.family, aes(x = Koala_Collection, y = Abundance,
                                        fill = fct_reorder(family_20, -Abundance))) +
  geom_bar(stat = "identity") +
  facet_wrap(~Population, scales = "free_x") +
  labs(x = "", y = "Relative abundance") +
#  scale_y_continuous(labels = scales::percent_format()) +
  theme(axis.text.y = element_text(size=16, face = 'bold'),
        axis.title.y = element_text(size=16, face = 'bold'),
        axis.ticks.y = element_line(size = 1),
        axis.text.x = element_text(size = 13, angle = 55, hjust = 1),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        legend.position = "top",
        strip.text = element_text(face = "bold", size = 14),
        panel.background = element_blank()
        ) +
  scale_fill_manual(values = 
      c("Bacteroidaceae" = "#228B22", "[Eubacterium]_coprostanoligenes_group" = "#3CB371",
        "Akkermansiaceae" = "#2E8B57", "Tannerellaceae" = "#8FBC8F",
        "Christensenellaceae" = "#191970", "Clostridiaceae" = "#db6d00",
        "Paludibacteraceae" = "#66CCEE", "Muribaculaceae" = "#FF1493",
        "Erysipelatoclostridiaceae" = "#0000FF", "Lachnospiraceae" = "#B8860B",
        "Oscillospiraceae" = "#FF6347", "Acidaminococcaceae" = "#F0E68C",
        "Pasteurellaceae" = "#FF69B4", "Desulfovibrionaceae" = "#FFC0CB",
        "Prevotellaceae" = "#FFFF00", "Rikenellaceae" = "#00FF7F",
        "Ruminococcaceae" = "#b66dff", "vadinHA49" = "#FF00FF",
        "Synergistaceae" = "#8B0000", "Gastranaerophilales" = "#000000", "Other" = "#808080")
  )

ggsave(filename = "output/Family_Taxa_Plot.png", 
       width = 20, height = 12, dpi = 300)

```

#Core microbiome analyses
```{r}



```

#Venn diagrams
```{r}
#Subset samples by population and save feature tables
ps.KI <- subset_samples(ps, Population == "Kangaroo Island")
ps.CL <- subset_samples(ps, Population == "Mainland SA")
ps.ML <- subset_samples(ps, Population == "Mountain_Lagoon")

ps.KI.table <- otu_table(ps.KI)
ps.CL.table <- otu_table(ps.CL)
ps.ML.table <- otu_table(ps.ML)

#For each ASV (row), if abundance > 0, print ASV (rowname) to a vector 
venn.KI <- rownames(ps.KI.table[ apply(ps.KI.table, MARGIN = 1, function(x) any(x > 0))])

venn.CL <- rownames(ps.CL.table[ apply(ps.CL.table, MARGIN = 1, function(x) any(x > 0))])

venn.ML <- rownames(ps.ML.table[ apply(ps.ML.table, MARGIN = 1, function(x) any(x > 0))])

ppn.comparison <- list("Kangaroo Island" = venn.KI, "Mainland SA" = venn.CL, 
                       "Mountain Lagoon" = venn.ML)

ppn.euler <- euler(ppn.comparison)

plot(ppn.euler,
     fills = c("Orange", "Red", "Blue"),
     edges = TRUE,
     fontsize = 10,
     quantities = list(fontsize=12, lwd = 10)
)

```



#Software/package versions
```{r}
sessionInfo()
```




